server:
  port: 8085

spring:
  application:
    name: Products
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:wookie_products
    username: wookie
    password: wookie_products
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
